name: calvano-replication
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - matplotlib=3.8.3
  - scipy=1.12.0
  - pandas=2.2.1
  - pytest=8.1.1
  - pytest-cov=4.1.0
  - sympy=1.12
  - numba=0.59.1
  - black=24.3.0
  - isort=5.13.2
  - flake8=7.0.0
  - tqdm=4.66.2
  - pyyaml=6.0.1
  - scikit-learn=1.4.1
  - seaborn=0.13.2
  - jupyter=1.0.0
  - ipykernel=6.29.3
  - sphinx=7.2.6
  - sphinx_rtd_theme=2.0.0
  - pip
  - pip:
    - ruff==0.3.4
    - mypy==1.9.0
